// Generated by CoffeeScript 1.6.2
(function() {
  var game, gfx, player;

  gfx = {
    init: function() {
      var canvasDOM;

      canvasDOM = document.getElementById("game");
      this.ctx = canvasDOM.getContext("2d");
      return this.ctx != null;
    }
  };

  game = {
    init: function() {
      if (!gfx.init()) {
        alert("Could not set up game canvas!");
      }
    }
  };

  game.init();

  ({
    init: function() {
      var canvas;

      canvas = document.querySelector("#game");
      this.ctx = canvas != null ? typeof canvas.getContext === "function" ? canvas.getContext("2d") : void 0 : void 0;
      if (!this.ctx) {
        return false;
      }
      this.w = canvas.width;
      this.h = canvas.height;
      return true;
    }
  });

  gfx.ctx.clearRect(0, 0, gfx.w, gfx.h);

  ({
    clear: function() {
      return this.ctx.clearRect(0, 0, this.w, this.h);
    }
  });

  player = {
    x: 10,
    y: 25,
    stats: {
      score: 1337
    },
    update: function(speed) {
      this.x += speed;
      return this.stats.score += 5;
    }
  };

}).call(this);
